error_log /home/rf/Projects/service-app/my-app/error.log;
pid /home/rf/Projects/service-app/my-app/nginx.pid;
events {}
http {
    include /etc/nginx/mime.types;
    access_log /home/rf/Projects/service-app/my-app/access.log;
    client_body_temp_path /home/rf/Projects/service-app/my-app/client_temp;
    proxy_temp_path /home/rf/Projects/service-app/my-app/proxy_temp;
    fastcgi_temp_path /home/rf/Projects/service-app/my-app/fastcgi_temp;
    uwsgi_temp_path /home/rf/Projects/service-app/my-app/uwsgi_temp;
    scgi_temp_path /home/rf/Projects/service-app/my-app/scgi_temp;
    server {
        listen 5173;
        server_name localhost;
        root /home/rf/Projects/service-app/my-app/dist;
        index index.html;
        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}
